linters:
  disable-all: true
  enable:
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - canonicalheader
    - containedctx
    - copyloopvar
    - decorder
    - dogsled
    # - dupl
    - dupword
    - durationcheck
    - errcheck
    - errchkjson
    - errname
    - exhaustive
    # - exptostd
    - fatcontext
    - ginkgolinter
    - gocheckcompilerdirectives
    - gochecknoinits
    - gochecksumtype
    # - gocognit
    - goconst
    - gocritic
    # - gocyclo
    # - godot
    - godox
    - goheader
    - gomoddirectives
    - gomodguard
    - goprintffuncname
    # - gosec
    - gosmopolitan
    - govet
    - grouper
    # - iface
    - importas
    - inamedparam
    - ineffassign
    - interfacebloat
    - nosprintfhostport
    - paralleltest
    - perfsprint
    - prealloc
    - predeclared
    - promlinter
    - protogetter
    - reassign
    # - recvcheck
    - revive
    - rowserrcheck
    - sloglint
    - spancheck
    - sqlclosecheck
    - staticcheck
    - tagalign
    - testableexamples
    - testifylint
    - thelper
    - tparallel
    - unconvert
    - unparam
    - unused
    - usestdlibvars
    # - usetesting
    - wastedassign
    - zerologlint

linters-settings:
  lll:
    line-length: 120

issues:
  exclude-rules:
    - path: "_test\\.go$"
      linters:
        - errcheck
        - paralleltest
        - gocritic
        - unconvert
        - intrange
    - path: "arenamanager_test.go"
      linters:
        - lll
  exclude-dirs:
    - third_party
    - builtin
    - examples
